name: Add codesandbox link

# Trigger the workflow only when a pull request is opened
on:
  pull_request:
    types: [opened]

jobs:
  codesandbox-comment:
    name: Add codesandbox link comment
    runs-on: ubuntu-latest
    steps:
      # Print debug info
      - name: Debug Info Codesandbox
        run: |
          echo "Starting Add codesandbox link job"
          env

      # Add CodeSandbox link as a comment on the pull request
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            You can check this code at CodeSandbox with the link
            https://githubbox.com/${{ github.repository }}/tree/${{ github.head_ref }}

      # Print debug info
      - name: Debug Info Codesandbox
        run: |
          echo "Add codesandbox link completed successfully"
